image: node

cache:
  paths:
    - .yarn
    - node_modules

stages:
  - init
  - lint

init:
  stage: init
  script:
    - npm install eslint @react-native-community/eslint-config

eslint:
  stage: lint
  script:
    - node_modules/eslint/bin/eslint.js .
