export const SET_VARIABLES = 'SET_VARIABLES';
export const SET_USER_INFO = 'SET_USER_INFO';
export const RESET_USER_INFO = 'RESET_USER_INFO';
export const SET_LAYOUT_SETTINGS = 'SET_LAYOUT_SETTINGS';
export const HIDE_FOOTER_APP = 'HIDE_FOOTER_APP';

export const SET_LOCATION_SEARCH = 'SET_LOCATION_SEARCH';
export const SET_HISTORIC_LOCATION_SEARCH = 'SET_HISTORIC_LOCATION_SEARCH';
export const SET_SPORT = 'SET_SPORT';
export const SET_LEAGUE = 'SET_LEAGUE';

export const SET_STEP0 = 'SET_STEP0';
export const SET_STEP1 = 'SET_STEP1';
export const SET_STEP2 = 'SET_STEP2';
export const RESET_CREATE_EVENT = 'RESET_CREATE_EVENT';

export const SET_ALL_EVENTS = 'SET_ALL_EVENTS';
export const ADD_FUTURE_EVENT = 'ADD_FUTURE_EVENT';
export const SET_GROUPS_EVENTS = 'SET_GROUPS_EVENTS';
export const DELETE_MY_EVENT = 'DELETE_MY_EVENT';
export const SET_PUBLIC_EVENTS = 'SET_PUBLIC_EVENTS';
export const SET_FUTURE_USER_EVENTS = 'SET_FUTURE_USER_EVENTS';
export const SET_PAST_USER_EVENTS = 'SET_PAST_USER_EVENTS';
export const SET_ALL_USER_EVENTS = 'SET_ALL_USER_EVENTS';

export const SET_INFO_GROUP_CREATE = 'SET_INFO_GROUP_CREATE';
export const SET_IMG_GROUP_CREATE = 'SET_IMG_GROUP_CREATE';
export const RESET_GROUPCREATE_DATA = 'RESET_GROUPCREATE_DATA';
export const SET_LOCATION_GROUP_CREATE = 'SET_LOCATION_GROUP_CREATE';

export const SET_MYGROUPS = 'SET_MYGROUPS';
export const EDIT_GROUP = 'EDIT_GROUP';
export const ADD_MY_GROUP = 'ADD_MY_GROUP';
export const DELETE_MY_GROUP = 'DELETE_MY_GROUP';
export const SET_ALL_GROUPS = 'SET_ALL_GROUPS';
export const SET_GROUPS_AROUND = 'SET_GROUPS_AROUND';

export const SET_CAPTAINS_CHALLENGE = 'SET_CAPTAINS_CHALLENGE';
export const SET_INFO_CHALLENGE = 'SET_INFO_CHALLENGE';
export const SET_DATE_CHALLENGE = 'SET_DATE_CHALLENGE';
export const SET_PRICE_CHALLENGE = 'SET_PRICE_CHALLENGE';
export const SET_LOCATION_CHALLENGE = 'SET_LOCATION_CHALLENGE';
export const SET_TEAMS_DATA = 'SET_TEAMS_DATA';
export const RESET_CHALLENGECREATE_DATA = 'RESET_CHALLENGECREATE_DATA';

export const SET_CONVERSATION = 'SET_CONVERSATION';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_INPUT = 'SET_INPUT';
export const ADD_IMAGE = 'ADD_IMAGE';
export const RESET_USER_MESSAGES = 'RESET_USER_MESSAGES';
export const DELETE_MY_CONVERSATION = 'DELETE_MY_CONVERSATION';

export const SET_COACH_SESSION_DATA = 'SET_COACH_SESSION_DATA';
export const RESET_COACH_DATA = 'RESET_COACH_DATA';
export const SET_CURRENT_COACHSESSION_ID = 'SET_CURRENT_COACHSESSION_ID';
export const SET_COACH_SESSION_DRAW_SETTINGS =
  'SET_COACH_SESSION_DRAW_SETTINGS';
export const SET_COACH_SESSION_SETTINGS = 'SET_COACH_SESSION_SETTINGS';

export const SET_LAYOUT = 'SET_LAYOUT';
