export const SET_BUILD_NUMBER = 'SET_BUILD_NUMBER';
export const TOGGLE_WIFI_AUTO_UPLOAD = 'TOGGLE_WIFI_AUTO_UPLOAD';
export const TOGGLE_RECORDING_PERMISSION = 'TOGGLE_RECORDING_PERMISSION';
export const SET_USER_INFO = 'SET_USER_INFO';
export const RESET_USER_INFO = 'RESET_USER_INFO';
export const SET_USER_CLOUD_ARCHIVES = 'SET_USER_CLOUD_ARCHIVES';
export const RESET_USER_CLOUD_ARCHIVES = 'RESET_USER_CLOUD_ARCHIVES';
export const SET_USER_SESSIONS = 'SET_USER_SESSIONS';
export const RESET_USER_SESSIONS = 'RESET_USER_SESSIONS';
export const SET_USER_SESSIONS_REQUESTS = 'SET_USER_SESSIONS_REQUESTS';
export const RESET_USER_SESSIONS_REQUESTS = 'RESET_USER_SESSIONS_REQUESTS';
export const SET_USER_NOTIFICATIONS = 'SET_USER_NOTIFICATIONS';
export const RESET_USER_NOTIFICATIONS = 'RESET_USER_NOTIFICATIONS';
export const SET_USER_BLOCKED_USERS = 'SET_USER_BLOCKED_USERS';
export const RESET_USER_BLOCKED_USERS = 'RESET_USER_BLOCKED_USERS';
export const SET_USER_BLOCKED_BY_USERS = 'SET_USER_BLOCKED_BY_USERS';
export const RESET_USER_BLOCKED_BY_USERS = 'RESET_USER_BLOCKED_BY_USERS';
export const SET_USER_SILENT_FRIENDS = 'SET_USER_SILENT_FRIENDS';
export const RESET_USER_SILENT_FRIENDS = 'RESET_USER_SILENT_FRIENDS';
export const SET_USER_CLUBS = 'SET_USER_CLUBS';
export const RESET_USER_CLUBS = 'RESET_USER_CLUBS';

export const SET_ARCHIVE = 'SET_ARCHIVE';
export const SET_ARCHIVES = 'SET_ARCHIVES';
export const DELETE_ARCHIVE = 'DELETE_ARCHIVE';
export const DELETE_ARCHIVES = 'DELETE_ARCHIVES';
export const RESET_ARCHIVES = 'RESET_ARCHIVES';
export const BIND_ARCHIVE = 'BIND_ARCHIVE';
export const SET_ARCHIVE_BINDED = 'SET_ARCHIVE_BINDED';
export const UNBIND_ARCHIVE = 'UNBIND_ARCHIVE';
export const RESET_CLOUD_ARCHIVES = 'RESET_CLOUD_ARCHIVES';
export const RESET_BINDS_ARCHIVES = 'RESET_BINDS_ARCHIVES';

export const SET_SESSION = 'SET_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';
export const RESET_SESSIONS = 'RESET_SESSIONS';
export const RESET_BINDS_SESSIONS = 'RESET_BINDS_SESSIONS';
export const BIND_SESSION = 'BIND_SESSION';
export const UNBIND_SESSION = 'UNBIND_SESSION';
export const SET_SESSION_BINDED = 'SET_SESSION_BINDED';

export const SET_CONVERSATION = 'SET_CONVERSATION';
export const SET_CONVERSATION_BINDED = 'SET_CONVERSATION_BINDED';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const BIND_CONVERSATION = 'BIND_CONVERSATION';
export const UNBIND_CONVERSATION = 'UNBIND_CONVERSATION';
export const RESET_BINDS_CONVERSATIONS = 'RESET_BINDS_CONVERSATIONS';

export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_INPUT = 'SET_INPUT';
export const ADD_IMAGE = 'ADD_IMAGE';
export const RESET_USER_MESSAGES = 'RESET_USER_MESSAGES';
export const DELETE_MY_CONVERSATION = 'DELETE_MY_CONVERSATION';

export const SET_COACH_SESSION_DATA = 'SET_COACH_SESSION_DATA';
export const RESET_COACH_DATA = 'RESET_COACH_DATA';
export const SET_CURRENT_COACHSESSION_ID = 'SET_CURRENT_COACHSESSION_ID';
export const SET_COACH_SESSION_DRAW_SETTINGS =
  'SET_COACH_SESSION_DRAW_SETTINGS';
export const SET_COACH_SESSION_SETTINGS = 'SET_COACH_SESSION_SETTINGS';
export const SET_SESSION_INFO = 'SET_SESSION_INFO';
export const SET_CURRENT_SESSION = 'SET_CURRENT_SESSION';
export const END_CURRENT_SESSION = 'END_CURRENT_SESSION';
export const UNSET_CURRENT_SESSION = 'UNSET_CURRENT_SESSION';
export const SET_RECORDING = 'SET_RECORDING';
export const SET_ALL_SESSIONS = 'SET_ALL_SESSIONS';
export const SET_CURRENT_SESSION_RECONNECTING =
  'SET_CURRENT_SESSION_RECONNECTING';

export const ENQUEUE_UPLOAD_TASK = 'ENQUEUE_UPLOAD_TASK';
export const ENQUEUE_UPLOAD_TASKS = 'ENQUEUE_UPLOAD_TASKS';
export const DEQUEUE_UPLOAD_TASK = 'DEQUEUE_UPLOAD_TASK';
export const START_UPLOAD_TASK = 'START_UPLOAD_TASK';
export const PAUSE_UPLOAD_TASK = 'PAUSE_UPLOAD_TASK';
export const RESUME_UPLOAD_TASK = 'RESUME_UPLOAD_TASK';
export const FINISH_UPLOAD_RASK = 'FINISH_UPLOAD_TASK';
export const SET_UPLOAD_TASK_PROGRESS = 'SET_UPLOAD_TASK_PROGRESS';
export const SET_UPLOAD_TASK_ERROR = 'SET_UPLOAD_TASK_ERROR';
export const MODIFY_UPLOAD_TASK = 'MODIFY_UPLOAD_TASK';
export const RESET_UPLOAD_QUEUE = 'RESET_UPLOAD_QUEUE';

export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_GENERAL_SESSION_RECORDING = 'SET_GENERAL_SESSION_RECORDING';
export const SET_CAMERA_AVAILABILITY = 'SET_CAMERA_AVAILABILITY';

export const ADD_USER_LOCAL_ARCHIVE = 'ADD_USER_LOCAL_ARCHIVE';
export const REMOVE_USER_LOCAL_ARCHIVE = 'REMOVE_USER_LOCAL_ARCHIVE';
export const REMOVE_USER_LOCAL_ARCHIVES = 'REMOVE_USER_LOCAL_ARCHIVES';
export const LEGACY_REMOVE_USER_LOCAL_ARCHIVE =
  'LEGACY_REMOVE_USER_LOCAL_ARCHIVE';

export const SET_CONNECTION_TYPE = 'SET_CONNECTION_TYPE';

export const SET_CLUBS = 'SET_CLUBS';
export const DELETE_CLUBS = 'DELETE_CLUBS';
export const RESET_CLUBS = 'RESET_CLUBS';
export const SET_CLUB = 'SET_CLUB';

export const SET_BOOKINGS = 'SET_BOOKINGS';
export const DELETE_BOOKINGS = 'DELETE_BOOKINGS';
export const RESET_BOOKINGS = 'RESET_BOOKINGS';

export const SET_SERVICES = 'SET_SERVICES';
export const DELETE_SERVICES = 'DELETE_SERVICES';
export const RESET_SERVICES = 'RESET_SERVICES';

export const SET_USER_BOOKINGS = 'SET_USER_BOOKINGS';
export const RESET_USER_BOOKINGS = 'RESET_USER_BOOKINGS';

export const SET_POSTS = 'SET_POSTS';
export const DELETE_POSTS = 'DELETE_POSTS';
export const RESET_POSTS = 'RESET_POSTS';

export const SET_USERS = 'SET_USERS';
export const RESET_USERS = 'RESET_USERS';
